trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
- group: AWS Secrets
- name: AWS_REGION
  value: 'us-east-1'
- name: BUCKET_NAME
  value: 'pragzoleta-deploy-manual'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
      dir dist
    displayName: 'Build Vite App y mostrar dist/'

  - powershell: |
      Invoke-WebRequest "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
      Start-Process msiexec.exe -Wait -ArgumentList '/i AWSCLIV2.msi /quiet'
    displayName: 'Instalar AWS CLI en Windows'

  - powershell: |
      $env:AWS_ACCESS_KEY_ID = "$(AWS_ACCESS_KEY_ID)"
      $env:AWS_SECRET_ACCESS_KEY = "$(AWS_SECRET_ACCESS_KEY)"
      aws configure set aws_access_key_id $env:AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $env:AWS_SECRET_ACCESS_KEY
      aws configure set default.region "$(AWS_REGION)"
      aws s3 sync dist/ s3://$(BUCKET_NAME) --delete
    displayName: 'Upload a S3 via PowerShell'
