trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Agente self-hosted en Windows

variables:
- group: AWS Secrets
- name: AWS_REGION
  value: 'us-east-1'
- name: BUCKET_NAME
  value: 'pragzoleta-deploy-manual'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - script: |
      call npm install
      call npm run build
    displayName: 'Compilar Vite (Windows)'

  - powershell: |
      Invoke-WebRequest "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
      Start-Process msiexec.exe -Wait -ArgumentList '/i AWSCLIV2.msi /quiet'
    displayName: 'Instalar AWS CLI (Windows)'

  - powershell: |
      $env:AWS_ACCESS_KEY_ID = "$(AWS_ACCESS_KEY_ID)"
      $env:AWS_SECRET_ACCESS_KEY = "$(AWS_SECRET_ACCESS_KEY)"
      $env:AWS_REGION = "$(AWS_REGION)"
      aws s3 sync .\dist\ s3://$(BUCKET_NAME) --region $env:AWS_REGION --delete
    displayName: 'Subir a S3 (Windows)'
