trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Instalar Node.js'

- script: |
    cd $(Build.SourcesDirectory)
    npm ci
    vite build
  displayName: 'Compilar proyecto'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS-S3-Deploy'
    awsRegion: 'us-east-1'
    awsCommand: 's3'
    awsSubCommand: 'ls'
    awsArguments: 's3://pragzoleta-deploy-manual'
  displayName: 'Configurar credenciales AWS'

- script: |
    cd $(Build.SourcesDirectory)
    dir dist
  displayName: 'Verificar contenido de dist/'

- script: |
    cd $(Build.SourcesDirectory)
    aws s3 sync dist/ s3://pragzoleta-deploy-manual/ --delete
  displayName: 'Subir a S3'
