trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  AWS_REGION: 'us-east-1'
  S3_BUCKET: 'pragzoleta-deploy-manual'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.19.0'
  displayName: 'Instalar Node.js 20.19.0'

- script: |
    cd $(Build.SourcesDirectory)
    npm ci
    npm run build
  displayName: 'Compilar proyecto (tsc + vite)'

- script: |
    cd $(Build.SourcesDirectory)
    dir dist
  displayName: 'Verificar contenido de dist/'

- script: |
    cd $(Build.SourcesDirectory)
    aws s3 sync dist/ s3://$(S3_BUCKET) --region $(AWS_REGION) --delete
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Subir frontend a S3'
