trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Instalar Node.js'

- script: |
    npm ci
    npm run build
  displayName: 'Compilar proyecto'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS-S3-Deploy'
    awsRegion: 'us-east-1'
  displayName: 'Configurar credenciales AWS'

- script: |
    aws s3 sync dist/ s3://pragzoleta-deploy-manual/ --delete
  displayName: 'Subir a S3'

